### ISSUE TITLE
The old shifters should get an alarm if there are no new shifters

### ISSUE THREAD

**Issue by adambrown1** [AG-Schumann/Doberman#121]
https://github.com/AG-Schumann/Doberman/blob/9b867c098e4dc755e32577e01aaf5097d921c7a7/Doberman/AlarmMonitor.py#L239

**Comment by jarongrigat** [comment]
Yes, good idea. This needs a little bit of restructuring then, since we can't send a logged alarm to specific people (only to current shifters), but still no big deal.

**Comment by jarongrigat** [comment]
Probably better anyway not to log notifications as alarms

**Comment by adambrown1** [comment]
This is fixed by now. Let's close it
