### ISSUE TITLE
Pipeline config instead of (or as well as) node config

### ISSUE THREAD

**Issue by adambrown1** [AG-Schumann/Doberman#164]
Most configuration values are appropriate for at least two nodes in a pipeline (the open and close eval nodes). It would be nice if they can be shared across the pipeline.

**Comment by darrylmasson** [comment]
> Most configuration values are appropriate for at least two nodes in a pipeline

I disagree strongly with the generality implied in this statement. It may be true for _some_ config values in _some_ nodes in _some_ pipelines, but generic solutions to address specific problems leads to unmaintainable code.

**Comment by adambrown1** [comment]
This is true for all currently existing pipelines. We have duplicate node_config values everywhere.

**Comment by darrylmasson** [comment]
This is because "all currently existing" pipelines were copy-pasted from one original one which made heavy use of duplicate config values. This does not imply a requirement, merely that one person decided to do it once and since then no one questioned this.

**Comment by adambrown1** [comment]
Is there a way to avoid duplicate config values? To be honest, I really don't care enough to keep arguing. But at some point we will only change the value in one of the two nodes' configurations and get annoyed. And I don't see the problem with having general pipeline config, and the statement "generic solutions to address specific problems leads to unmaintainable code" is a generic reply to a specific suggestion, which I would argue leads to unmaintainable disussions 😀

**Comment by adambrown1** [comment]
Fixed by #165
