### ISSUE TITLE
Logs are useless

### ISSUE THREAD

**Issue by florian-toennies** [AG-Schumann/Doberman#175]
![useless log](https://user-images.githubusercontent.com/9748173/161292271-a5d95ac3-dcdb-4590-a7c8-d3adb16832d2.jpg)

can you please add the pipeline name after the pipeline flavor so you can actually find the error in a specific pipeline??
(or have a per piepline logfile eg: f"pl_{flavor}_{pipelinename}"

maybe also add ability to turn off logs for pipelines in case they run smoothly....

**Comment by jarongrigat** [comment]
Well, so it took me about 30s to find your problem in the log file. I guess "useless" is a strong word for you not looking properly ;) Anyway, I agree that it would be nice to have the pipeline name in the log for all the greppage you might want to do.

**Comment by florian-toennies** [comment]
well I tried to tail -f the logfile but the other pieplines send so much information that I could not figure out which message was for my pipeline and which not. Also silencing the other pipelines did not prevent them from loggin....
