### ISSUE TITLE
Can't start alarm pipelines

### ISSUE THREAD

**Issue by adambrown1** [AG-Schumann/Doberman#193]
e.g. the following error messages after starting on website, logged in

`Could not build pipeline alarm_P_IC_03, check debug logs, <class 'AttributeError'>: module 'Doberman' has no attribute 'DeviceRespondingAlarm'`

**Comment by jarongrigat** [comment]
This is due to the fact that Doberman has no attribute DeviceRespondingAlarm. I fixed the Make new alarm button on the website/
