### ISSUE TITLE
Alarms in the night

### ISSUE THREAD

**Issue by adambrown1** [AG-Schumann/Doberman#198]
Often new data seems to unavailable for some time in the night - all active alarm pipelines give a "no new value" alarm. For example,
15.10.22 01:30:54
17.10.22 01:31:03

Presumably the timestamps are not a coincidence!

**Comment by TiffanyLuce** [comment]
20.10.22 00:00:25 for the system
same thing happened but with really different log error messages

**Comment by adambrown1** [comment]
Given that these alarms are probably due to the server or network being busy at that time, and that we haven't had one for a while since #202 has been tested on the live branch, we can probably close it when we merge that PR.
