### ISSUE TITLE
Hypervisor not restarting reliably

### ISSUE THREAD

**Issue by adambrown1** [AG-Schumann/Doberman#199]
e.g. revpi3 not restarted on 10.17.22 from 08:58 GMT for more than one hour

**Comment by jarongrigat** [comment]
Seems like revpi3 was not managed by the hypervisor when I just checked. Was it during the period you mention? Otherwise this is expected behavior. Only devices managed by the hypervisor will be restarted.

**Comment by adambrown1** [comment]
Hmm possibly it was not, I didn't check. Is there ever a need to have something not managed? It will tend to lead to situations like this where we don't realise it is unmanaged.
