### ISSUE TITLE
Add alarm via doberman device output

### ISSUE THREAD

**Issue by adambrown1** [AG-Schumann/Doberman#216]
We would like a flashing light in the lab when there is a doberman alarm, for which we could use a revpi digital output. Therefore it would be good to have an alarm function that sends via a doberman device.

**Comment by adambrown1** [comment]
I guess queued commands are no longer available. One option is to have a pipeline control the output, which is activated or configured when an alarm is triggered (as a new alarm protocol). This could then turn off the output after some time.

Or somehow to check whether there is a silenced pipeline since this indicates an alarm is active? Or to turn off the active alarm output when a pipeline is reactivated?

**Comment by jarongrigat** [comment]
Okay, I thought about it and I think my favourite solution is the following:

- Add a field `alarm_is_triggered: True/False` to each sensor's DB entry.
- Make AlarmNodes set this field accordingly. This can be down regardless of the pipeline being silent or active.
- Create a new Node that checks whether there are triggered alarms or not. Maybe this can the option of either looking at a list of sensors or looking for any alarms or something like this.
What do you think?

**Comment by adambrown1** [comment]
That sounds good to me. I also like the idea we could have an output that is only affected by alarms on a subset of sensors
