### ISSUE TITLE
Add more info to alarm emails

### ISSUE THREAD

**Issue by darrylmasson** [AG-Schumann/Doberman#35]
Currently just says "hey something went wrong here." In principle we could also have it attach a plot saying "here's what this sensor has been doing for the past ___ minutes" or something along that line.

**Comment by adambrown1** [comment]
My suggestion:
  * Plots are left to doberview2, we don't create a plot in doberman and therefore don't attach it to the email
  * Emails contain a set of links, which can be configured in the database. This way doberman knows which address to hit for each link. Possible examples are: Sensor details page, Silence for 1 hour.

What do you think @jarongrigat?

**Comment by jarongrigat** [comment]
Yes, I agree.
