### ISSUE TITLE
PID control rudimentary

### ISSUE THREAD

**Issue by darrylmasson** [AG-Schumann/Doberman#41]
We don't deal with, for instance, integral windup, or setpoint stepping, or have gain scheduling. The current implementation is probably good enough to maintain a system near its setpoint, but would probably have difficulty in getting the system there in the first place.

**Comment by darrylmasson** [comment]
Also be sure to accept negative integral gain

**Comment by adambrown1** [comment]
We now have pipelines, which support derivative and integral nodes. It would be possible to construct a PID system without any changes to doberman. However, we haven't so far had the need for one. I suggest closing this as not planned for now, unless you see a strong reason for explicitly adding a PID node @jarongrigat @TiffanyLuce

**Comment by jarongrigat** [comment]
There is no need for a PID Node. As you say, you can just use the P, I, and D. Then you can use an EvalNode and a AnalgControlNode to do the rest.
