### ISSUE TITLE
Plugins can die in strange edge-cases

### ISSUE THREAD

**Issue by darrylmasson** [AG-Schumann/Doberman#48]
Not sure why or how (possibly unhandled SIGKILLs). Doberman should see what plugins are normally running and restart them when they die

**Comment by ramirezdiego** [comment]
MongoDB queries looking for the time syntax? If elapsed time > 5mins, restart plugin...?

**Comment by darrylmasson** [comment]
Basically. I was thinking of adding a heartbeat to the normal sensor operation, and if Doberman sees that a plugin is nominally running but it hasn't sent a heartbeat within the last ____ seconds, it restarts it.

**Comment by ramirezdiego** [comment]
So a real heartbeat, hahaha :smile: !
