### ISSUE TITLE
Testing difficult in production environment

### ISSUE THREAD

**Issue by darrylmasson** [AG-Schumann/Doberman#76]
The lack of a dummy controller that emulates `<insert controller type here>` without actually needing hardware access makes testing difficult when the system is running, and downtime often isn't sufficient to do the necessary testing and debugging.

**Comment by ramirezdiego** [comment]
Poor graduate students reviewing PRs agree with that statement.

**Comment by darrylmasson** [comment]
#77 is a step towards this but the `TestSensor` server doesn't respond as desired. I probably don't understand sockets in python properly.

**Comment by darrylmasson** [comment]
I followed the examples in the python docs and got the TestSensor server working properly. We now have a working LAN emulator, maybe worth looking into a serial emulator later.

**Comment by darrylmasson** [comment]
Some new stuff got added into the TestSensor while working on #90, which should scope-complete this issue.

**Comment by darrylmasson** [comment]
Closed via #90
