### ISSUE TITLE
Dynamic sensor activation

### ISSUE THREAD

**Issue by darrylmasson** [AG-Schumann/Doberman#79]
For sensors (and, more generally, entire systems) that don't run with 100% uptime, a dynamic activation routine would reduce operator involvement and ensure data is collected. For instance, if a HV channel isn't on, there isn't any need to query anything other than its state (unless we particularly want to fill the database with useless data). When the system detects that the channel has been activated, there is now a need to monitor the voltage, current, etc of that channel. When the channel is deactivated, the need disappears. This removes the need for the operator to activate and deactivate sensors, which is guaranteed to be forgotten.

**Comment by adambrown1** [comment]
Don't see a big need for this. Suggest closing as not planned, unless you particularly want to create the corresponding pipeline node @jarongrigat @TiffanyLuce

**Comment by jarongrigat** [comment]
I agree. There is really no problem in storing too much data.
