### ISSUE TITLE
More intelligent waiting for sensors to respond

### ISSUE THREAD

**Issue by darrylmasson** [AG-Schumann/Doberman#83]
The SendRecv method waits for a pre-defined amount of time between sending and receiving (1 second for Serial devices + 0.2 seconds after receiving, 10ms for ethernet sensors). For the isegNHQ the wait is between sending individual characters. It would be better to specify the token that ends the message from a controller, and read until that is received.

**Comment by jarongrigat** [comment]
I think it would be a more robust way of doing it. I'll have a try.
