### ISSUE TITLE
Catch database timeouts

### ISSUE THREAD

**Issue by darrylmasson** [AG-Schumann/Doberman#89]
If the database dies for whatever reason, queries will timeout after 30 seconds. This is caught like any other unexpected exception, but then the system just shuts off. We should make a special exception case for this exception to tell the system to begin automatic emergency shutdown procedures.

**Comment by adambrown1** [comment]
@jarongrigat I have no idea whether this is still and issue or what it means in real terms, but it has been open for three years and we should probably either close it or fix it!

**Comment by jarongrigat** [comment]
Well I'm not so sure how to handle this. Data and commands can in principle already be distributed without the database. So maybe adding a DatabasePingNode that then triggers some commands to the system makes sense. for the worst worst case... not really seeing this happen ever.

**Comment by adambrown1** [comment]
In that case I suggest we close it
